version: '3'

services:
  authentication-service:
    platform: 'linux/amd64'
    image: 'authentication-service:latest'
    container_name: authentication-service
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    depends_on:
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=user_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8081
    expose:
      - "8081"
    ports:
      - "8081:8081"
  rabbitmq-producer-service:
    platform: 'linux/amd64'
    image: 'rabbitmq-producer-service:latest'
    container_name: rabbitmq-producer-service
    build:
      context: ./rabbitmq-producer-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_VIRTUAL-host=/
    expose:
      - "8084"
    ports:
      - "8084:8084"
  rabbitmq-consumer-service:
    platform: 'linux/amd64'
    image: 'rabbitmq-consumer-service:latest'
    container_name: rabbitmq-consumer-service
    build:
      context: ./rabbitmq-consumer-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      #      port for amqp(advance message queueing protocol)
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_VIRTUAL-host=
    expose:
      - "8086"
    ports:
      - "8086:8086"
  department-service:
    platform: 'linux/amd64'
    image: 'department-service:latest'
    container_name: department-service
    build:
      context: ./department-service
      dockerfile: Dockerfile
    depends_on:
      - department-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://department-db:5432/department_db
      - SPRING_DATASOURCE_USERNAME=department_db
      - SPRING_DATASOURCE_PASSWORD=department_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8087
    expose:
      - "8087"
    ports:
      - "8087:8087"
  person-service:
    platform: 'linux/amd64'
    image: 'person-service:latest'
    container_name: person-service
    build:
      context: ./person-service
      dockerfile: Dockerfile
    depends_on:
      - person-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://person-db:5432/person_db
      - SPRING_DATASOURCE_USERNAME=person_db
      - SPRING_DATASOURCE_PASSWORD=person_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8088
    expose:
      - "8088"
    ports:
      - "8088:8088"
  kafka-producer-service:
    platform: 'linux/amd64'
    image: 'kafka-producer-service:latest'
    container_name: kafka-producer-service
    build:
      context: kafka-producer-service
      dockerfile: Dockerfile
    depends_on:
      - broker
    environment:
      - SERVER_PORT=8089
      - SPRING_KAFKA_CONSUMER_GROUP-ID=tpd-logger
      - SPRING_KAFKA_CONSUMER_AUTO-OFFSET-RESET=earliest
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=PLAINTEXT://broker:29092
      - tpd.topic-name=advice-topic
      - tpd.messages-per-request=10
      - spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
      - spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
    expose:
      - "8089"
    ports:
      - "8089:8089"
  kafka-consumer-service:
    platform: 'linux/amd64'
    image: 'kafka-consumer-service:latest'
    container_name: kafka-consumer-service
    build:
      context: kafka-consumer-service
      dockerfile: Dockerfile
    depends_on:
      - broker
    environment:
      - SERVER_PORT=8090
      - SPRING_KAFKA_CONSUMER_GROUP-ID=tpd-logger
      - SPRING_KAFKA_CONSUMER_AUTO-OFFSET-RESET=earliest
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=PLAINTEXT://broker:29092
      - tpd.topic-name=advice-topic
      - tpd.messages-per-request=10
    expose:
      - "8090"
    ports:
      - "8090:8090"
  user-db:
    image: 'postgres:15-alpine'
    container_name: user-db
    environment:
      - POSTGRES_USER=user_db
      - POSTGRES_PASSWORD=user_db
      - POSTGRES_DB=user_db
    volumes:
      - user_db:/var/lib/postgresql/data
    ports:
      - "5438:5432"
  department-db:
    image: 'postgres:15-alpine'
    container_name: department-db
    environment:
      - POSTGRES_USER=department_db
      - POSTGRES_PASSWORD=department_db
      - POSTGRES_DB=department_db
    volumes:
      - department_db:/var/lib/postgresql/data
    ports:
      - "5439:5432"
  person-db:
    image: 'postgres:15-alpine'
    container_name: person-db
    environment:
      - POSTGRES_USER=person_db
      - POSTGRES_PASSWORD=person_db
      - POSTGRES_DB=person_db
    volumes:
      - person_db:/var/lib/postgresql/data
    ports:
      - "5440:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-local'
    expose:
      - "15672"
      - "5672"
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbit_mq1:/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - rabbit_mq2:/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
volumes:
  user_db:
  department_db:
  person_db:
  rabbit_mq1:
  rabbit_mq2: