GET localhost:8088/api/v1/persons/test
###

GET localhost:8088/api/v1/persons
###

POST localhost:8088/api/v1/persons
Content-Type: application/json

{
  "firstName": "Fajrik",
  "lastName": "Illahi",
  "email": "fajri.illahiITB@gmail.com",
  "departmentId": 5
}

###
POST https://person-service-beyonder12.cloud.okteto.net/api/v1/persons
Content-Type: application/json

{
"firstName": "Fajri",
"lastName": "Illahi",
"email": "fajri.illahiITB@gmail.com",
"departmentId": 1
}

###
GET localhost:8088/api/v1/persons/2
###

GET https://person-service-beyonder12.cloud.okteto.net/api/v1/persons/2
###