GET localhost:8080/api/v1/companies

###

POST localhost:8080/api/v1/companies
Content-Type: application/json

{
  "name" : "ikon"
}

###

POST localhost:8080/api/v1/companies/6/employees
Content-Type: application/json

{
  "name": "joko connors"
}