apiVersion: v1
kind: Service
metadata:
  name: {{ include "crud-springboot.fullname" . }}
  labels:
    {{- include "crud-springboot.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crud-springboot.selectorLabels" . | nindent 4 }}
