GET localhost:8082/api/v1/books

###

GET localhost:8080/api/v1/books/2

###
POST localhost:8080/api/v1/books
Content-Type: application/json

{
  "author" : "Irfan",
  "name" : "Love in one night"
}

###
PUT localhost:8080/api/v1/books/1
Content-Type: application/json

{
  "author" : "Irfan",
  "name" : "Love in one night"
}

###

DELETE localhost:8080/api/v1/books/3

### person
POST localhost:8080/api/v1/persons
Content-Type: application/json

{
  "name": "Fajri Doe",
  "street": "123 Main St",
  "city": "San Francisco",
  "state": "CA",
  "zipCode": "94105"
}

###
GET localhost:8080/api/v1/persons/16

###
GET localhost:8082/actuator/info

###
GET localhost:8082/actuator/health

###
GET localhost:8082/actuator
